declare module 'appHeader/Header'
declare module 'appDashboard/Dashboard'
declare module 'appTransactions/Transactions'
declare module 'utilUi/ThemeProvider'
declare module 'utilStore/stores/history'
